<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/02/13 12:51:46

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=test',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
